<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tex [
<!ELEMENT tex (node*)>
<!ELEMENT node ((key, from, to, requires?)*)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT requires (location*)>
<!ELEMENT location (#PCDATA)>

<!ATTLIST location position (start|content|end) "content">
]>

<!-- Tags: html, head, body, title, author, h1, h2, h3, hr, br, table, th, tr, 
td, b, a, dl, dt, dd, font, noscript, script, ul, li, link,!doctype -->

<tex>

<!-- html -->
<node>
  <key>
   html
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[ 
    ]]>
  </to>
</node>
</tex>

<!-- head  -->
<node>
  <key>
   head
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[
    ]]>
  </to>
  <requires>
    <location position="start">
     <![CDATA[
    \documentclass[
    a4paper,% DIN A4
    fontsize=12pt		% Schriftgröße 12 Punkt
    ]{scrartcl}                 % 'article' aus dem 'Koma'-Script
]]>
    </location>
  </requires>
</node>
</tex>

<!-- title -->
<node>
  <key>
   title
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[
    ]]>
  </to>
  <requires>
    <location position="start">
     <![CDATA[\title{----CONTENT----}]]>
    </location>
  </requires>
</node>
</tex>


<!-- body  -->
<node>
  <key>
   body
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[
    \begin{document}
----CONTENT----
\end{document}
    ]]>
  </to>
</node>
</tex>


<!-- author -->
<node>
  <key>
   author
  </key>
  <from>
    <![CDATA[<
----TEXT----
    ]]>
  </from>
  <to>
    <![CDATA[
    ]]>
  </to>
  <requires>
    <location position="start">
     <![CDATA[\author{----CONTENT----}]]>
    </location>
  </requires>
</node>
</tex>


<!-- h1 -->
<node>
<key>
  h1
</key>
  <from>
    <![CDATA[<INHALT]]>
  </from>
  <to>
    <![CDATA[\section{
    INHALT
    }]]>
  </to>
</node>
</tex>

<!-- h2 -->
<node>
<key>
  h2
</key>
  <from>
    <![CDATA[<INHALT]]>
  </from>
  <to>
    <![CDATA[\subsection{
    INHALT]]>
    }
  </to>
</node>
</tex>

<!-- h3 -->
<node>
<key>
  h1
</key>
  <from>
    <![CDATA[<INHALT]]>
  </from>
  <to>
    <![CDATA[\subsubsection{
    INHALT
    }]]>
  </to>
</node>
</tex>

<!-- br  -->
<node>
  <key>
   br
  </key>
  <from>
  </from>
  <to>
    <![CDATA[
    \newline
    ]]>
  </to>
</node>
</tex>

<!-- p  -->
<node>
  <key>
   p
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[
    
----CONTENT----

    ]]>
  </to>
</node>
</tex>

<!-- table  -->
<node>
  <key>
   table
  </key>
  <from>
    <![CDATA[INHALT]]>
  </from>
  <to>
    <![CDATA[begin{longtable}{|p{.2textwidth}|p{.8textwidth}|}
    hline
    INHALT
    end{longtable}]]>
  </to>
  <requires>
    <location position="start">
     <![CDATA[\usepackage{longtable}]]>
    </location>
  </requires>
</node>

<!-- th  -->
<node>
  <key>
   th
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[
----CONTENT----&----CONTENT---- \\ \hline \endhead
    ]]>
  </to>
</node>
</tex>

<!-- tr 
hier wirds kompliziert:
das sind 2 Spalten und vier Zeilen,
in der letzten Zeile wird nicht mit "\\"
abgeschlossen und zwischen den Zellen steht ein "&"
× & ×\\
× & ×\\
× & ×\\
× & ×
-->
<node>
  <key>
   tr
  </key>
  <from>
    <![CDATA[<
<td>----CONTENT----</td>&<td>----CONTENT----</td>
    ]]>
  </from>
  <to>
    <![CDATA[
----CONTENT----&----CONTENT---- \\ \hline
    ]]>
  </to>
</node>
</tex>

<!-- b  -->
<node>
  <key>
   b
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[
    \textbf{----CONTENT----}
    ]]>
  </to>
</node>
</tex>

<!-- a 
wenn alles in eine datei geschrieben werden soll, dann wird es nicht gebraucht,
sonst eine weitere .tex-Datei erstellen und einbinden
-->
<node>
  <key>
   a
  </key>
  <from>
    <![CDATA[<
----HREF----
    ]]>
  </from>
  <to>
    <![CDATA[
    \input{----HREF----.tex}
    ]]>
  </to>
</node>
</tex>

<!-- dl  -->
<node>
  <key>
   dl
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[
    \begin{description}
----CONTENT----
 \textbf{}\end{description}
    ]]>
  </to>
</node>
</tex>

<!-- dt  -->
<node>
  <key>
   dt
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[
    \item[----CONTENT----]
    ]]>
  </to>
</node>
</tex>

<!-- dd
fehlte in der ursprünglichen Liste der Tags... -->
<node>
  <key>
   dd
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[
----CONTENT----
    ]]>
  </to>
</node>
</tex>

<!-- ul  -->
<node>
  <key>
   ul
  </key>
  <from>
    <![CDATA[<

    ]]>
  </from>
  <to>
    <![CDATA[
\begin{itemize}
----CONTENT---- 
\end{itemize}
    ]]>
  </to>
</node>
</tex>

<!-- li -->
<node>
  <key>
   li
  </key>
  <from>
    <![CDATA[<
    ]]>
  </from>
  <to>
    <![CDATA[
\item ----CONTENT----
    ]]>
  </to>
</node>
</tex>

<!-- font -->
<node>
  <key>
   font
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[
----CONTENT----
    ]]>
  </to>
</node>
</tex>

<!-- noscript -->
<node>
  <key>
   noscript
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[
    ]]>
  </to>
</node>
</tex>

<!-- script -->
<node>
  <key>
   script
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[
    ]]>
  </to>
</node>
</tex>

<!-- link -->
<node>
  <key>
   link
  </key>
  <from>
    <![CDATA[<
----CONTENT----
    ]]>
  </from>
  <to>
    <![CDATA[
    ]]>
  </to>
</node>
</tex>
